
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "newPassword"
    ports:
      - "5432:5432"  
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: newPassword
    ports:
      - "27017:27017"